config/routes.rb
Rails.application.routes.draw do
	resources :users do
		# collection do
		# 	get "signin"
		# end
	end

	get "/signin", to: "users#signin"
	post "/authenticate", to: "users#authenticate"
	delete "/logout", to: "users#logout"


	root to: "users#index"
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user_id
end

app/models/account_history.rb
class AccountHistory < ApplicationRecord
  belongs_to :acc_id
end

app/models/account_history2.rb
class AccountHistory2 < ApplicationRecord
  belongs_to :acc_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	# validation
	validates :name, presence: true, exclusion: { in: %w(admin superuser)}
	validates :email, presence: true, uniqueness: true
	validates :password, presence: true, length: { maximum: 100, minimum: 4 }, on: :create
	validates :confirm_password, presence: true, length: { maximum: 100, minimum: 4 }, on: :create

	# custom validate methods
	validate :verify_password
	def verify_password
		if password != confirm_password
			errors.add(:base, "Password and Confirm Password are not matching")
		end
	end

	before_destroy :write_into_json
	def write_into_json
		logger.info("Creating a file")
		File.open("#{Rails.root}/public/users#{self.id}.json", "w") { |foo|
			foo.write(self.to_json) 
		}
	end

	before_save do
		# self.name = "fname" + name
	end

	before_save :encrypt_password
	def encrypt_password
		self.password = Digest::MD5.hexdigest(password)
		self.confirm_password = Digest::MD5.hexdigest(confirm_password)
	end

	def self.auth(email, password)
		where(email: email, password: Digest::MD5.hexdigest(password)).last
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :verify_session, except: [:new, :create, :signin, :authenticate]

	def index
		cookies[:name] = {value: "Rails"}
		@user = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to users_path
		else
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to users_path
		else
			render :edit
		end
	end

	def show
		@user = User.find(params[:id])
	end
	
	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:notice] = "User: '#{@user.name}' deleted successfully!" 
		redirect_to users_path
	end

	def authenticate
		@user = User.auth(params[:email], params[:password])
		if @user
			session[:user_id] = @user.id
			flash[:notice] = "Logged in as: #{@user.name}"
			redirect_to users_path
		else
			flash[:notice] = "Invalid Username/Email or Password"
			redirect_to signin_path
		end
	end

	def verify_session
		if session[:user_id].nil?
			redirect_to signin_path
		end
	end

	def logout
		session[:user_id] = nil
		redirect_to signin_path
	end

	protected
	def user_params
		params.require(:user).permit!
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleRailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless session[:user_id].nil? %>
    <%= link_to "Logout", logout_path, method: :delete %>
    <%end%>

    <% flash.each do | _, value | %>
    <%= value%>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_for @user do | f |%>
<table>
	<tr>
		<td><%= f.label :name%></td>
		<td><%= f.text_field :name%></td>
	</tr>
	<tr>
		<td><%= f.label :email%></td>
		<td><%= f.email_field :email%></td>
	</tr>
	<tr>
		<td></td>
		<td><%= f.submit "Update"%></td>
	</tr>
</table>
<%end%>

<%= link_to "Home", users_path %>

app/views/users/index.html.erb
<table>
	<tr>
		<th>Name</th>
		<th>Email</th>
	</tr>
	<% @user.each do | user | %>
	<tr>
		<td><%= user.name %></td>
		<td><%= user.email %></td>
		<td><%= link_to "Edit", edit_user_path(user) %></td>
		<td><%= link_to "Show", user_path(user) %></td>
		<td><%= link_to "Delete", user, method: :delete, data: {confirm: "Are you sure to delete the user: '#{user.name}' with ID: '#{user.email}'?"} %></td>
	</tr>
	<%end%>
</table>

<%= link_to "Add New User", new_user_path %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
	<% @user.errors.messages.each do | key, merror | %>
		<%= key.to_s + ": " + merror[0] %>
	<%end%>
<%end%>


<%= form_for @user do | f|%>
	<table>
		<tr>
			<td><%= f.label :name%></td>
			<td><%= f.text_field :name%></td>
		</tr>
		<tr>
			<td><%= f.label :email%></td>
			<td><%= f.email_field :email%></td>
		</tr>
		<tr>
			<td><%= f.label :password%></td>
			<td><%= f.password_field :password%></td>
		</tr>
		<tr>
			<td><%= f.label :confirm_password%></td>
			<td><%= f.password_field :confirm_password%></td>
		</tr>
		<tr>
			<td></td>
			<td><%= f.submit "Sign Up"%></td>
		</tr>
	</table>
<%end%>

<%= link_to "Home", users_path %>

app/views/users/show.html.erb
<table>
	<tr>
		<th>Name</th>
		<th>Email</th>
	</tr>
	<tr>
		<td><%= @user.name %></td>
		<td><%= @user.email %></td>
		<td><%= link_to "Edit", edit_user_path(@user) %></td>
	</tr>
</table>

<%= link_to "Home", users_path %>
<%= link_to "Add New user", new_user_path %>

app/views/users/signin.html.erb
<%= form_tag action: :authenticate, method: :post do %>
	<table>
		<tr>
			<td><%= label_tag :email %></td>
			<td><%= text_field_tag :email %></td>
		</tr>
		<tr>
			<td><%= label_tag :password %></td>
			<td><%= password_field_tag :password %></td>
		</tr>
		<tr>
			<td></td>
			<td><%= submit_tag "Sign In" %></td>
		</tr>
	</table>
<%end%>